# .reviewer-config.sh — claude-code-reviewer configuration
# Generated by install.sh on 2026-04-22
# Edit to match your project. Source: https://github.com/jazzsequence/claude-code-reviewer
#
# shellcheck shell=bash
# shellcheck disable=SC2034  # All variables are used by the sourcing pre-commit hook.

REVIEWER_TEST_CMD="composer test"
REVIEWER_LINT_CMD="composer lint"
REVIEWER_BUILD_CMD="npm run build"
REVIEWER_E2E_CMD=""

REVIEWER_MAX_FILES=5
REVIEWER_MAX_INSERTIONS=500
REVIEWER_APPROVAL_TIMEOUT=300
REVIEWER_APPROVAL_FILE="reviewer-approved"

REVIEWER_TEXT_ONLY_PATTERN='\.(md|txt|rst)$'
REVIEWER_EXCLUDED_FILES='^package-lock\.json$|^yarn\.lock$|^pnpm-lock\.yaml$|^composer\.lock$|^Gemfile\.lock$'
